### ISSUE TITLE
stworzenie rozwiazania by drogi mogły być pod kątem

### ISSUE THREAD

**Issue by KKarol01** [Mateusz3124/Proceduralne-generowanie-miasta#13]
nieaktualne: to najlepiej przed piatkiem 1 grudnia bo ja bym tak zrobil ze najpierw tworze drogi a potem dostosuje sie do tego teren

**Comment by Mateusz3124** [comment]
z powodu zmiany pomysłu najpierw tworzymy teren a potem dostosowujemy drogi
